from sqlalchemy import Column, Integer, String, Numeric, Boolean
from .database import Base

class AccountMaster(Base):
    __tablename__ = 'nt_1_accountmaster'
    
    Ac_Code = Column(Integer, nullable=True)
    Ac_Name_E = Column(String(255), nullable=True)
    Ac_Name_R = Column(String(255), nullable=True)
    Ac_type = Column(String(5), nullable=True)
    Ac_rate = Column(Numeric(18, 2), nullable=True)
    Address_E = Column(String(255), nullable=True)
    Address_R = Column(String(255), nullable=True)
    City_Code = Column(Integer, nullable=True)
    Pincode = Column(String(10), nullable=True)
    Local_Lic_No = Column(String(255), nullable=True)
    Tin_No = Column(String(255), nullable=True)
    Cst_no = Column(String(255), nullable=True)
    Gst_No = Column(String(255), nullable=True)
    Email_Id = Column(String(255), nullable=True)
    Email_Id_cc = Column(String(255), nullable=True)
    Other_Narration = Column(String(1000), nullable=True)
    ECC_No = Column(String(255), nullable=True)
    Bank_Name = Column(String(255), nullable=True)
    Bank_Ac_No = Column(String(255), nullable=True)
    Bank_Opening = Column(Numeric(18, 2), nullable=True)
    bank_Op_Drcr = Column(String(1), nullable=True)
    Opening_Balance = Column(Numeric(18, 2), nullable=True)
    Drcr = Column(String(1), nullable=True)
    Group_Code = Column(Integer, nullable=True)
    Created_By = Column(String(255), nullable=True)
    Modified_By = Column(String(255), nullable=True)
    Short_Name = Column(String(50), nullable=True)
    Commission = Column(Numeric(18, 2), nullable=True)
    carporate_party = Column(String(1), nullable=True)
    referBy = Column(String(100), nullable=True)
    OffPhone = Column(String(500), nullable=True)
    Fax = Column(String(500), nullable=True)
    CompanyPan = Column(String(500), nullable=True)
    AC_Pan = Column(String, nullable=True)
    Mobile_No = Column(String(50), nullable=True)
    Is_Login = Column(String(1), nullable=True)
    IFSC = Column(String(50), nullable=True)
    FSSAI = Column(String(50), nullable=True)
    Branch1OB = Column(Numeric(18, 2), nullable=True)
    Branch2OB = Column(Numeric(18, 2), nullable=True)
    Branch1Drcr = Column(String(1), nullable=True)
    Branch2Drcr = Column(String(1), nullable=True)
    Locked = Column(Boolean, nullable=True)
    GSTStateCode = Column(Integer, nullable=True)
    UnregisterGST = Column(Boolean, nullable=True)
    Distance = Column(Numeric(18, 2), nullable=True)
    Bal_Limit = Column(Numeric(18, 2), nullable=True)
    accoid = Column(Integer, primary_key=True, nullable=False)
    bsid = Column(Integer, nullable=True)
    cityid = Column(Integer, nullable=True)
    whatsup_no = Column(String(45), nullable=True)
    company_code = Column(Integer, nullable=True)
    adhar_no = Column(String(20), nullable=True)
    Limit_By = Column(String(2), nullable=True)
    Tan_no = Column(String(100), nullable=True)
    TDSApplicable = Column(String(1), nullable=True)
    PurchaseTDSApplicable = Column(String(1), nullable=True)
    PanLink = Column(String(500), nullable=True)

    def __repr__(self):
        return f"<AccountMaster {self.accoid} - {self.Ac_Name_E}>"