import { useState, useEffect } from 'react';
import TableUtility from "../../common/TableUtility/TableUtility";
import Modal from '../../common/Modal/Modal';
import CreateNewButton from "../../common/Buttons/AddButton";
import { PencilSquareIcon, CheckCircleIcon, XCircleIcon } from '@heroicons/react/24/outline';
import { Trash2 } from 'lucide-react';

import {
    useGetSlotMastersQuery,
    useGetMaxSlotMasterIdQuery,
    useAddSlotMasterMutation,
    useUpdateSlotMasterMutation,
    useDeleteSlotMasterMutation
} from '../../services/slotMasterApi';

function SlotMaster() {
    const [isModalOpen, setIsModalOpen] = useState(false);
    const [formData, setFormData] = useState({
        SlotMaster_Name: '',
        SponsorMasterId: ''
    });

    const [editId, setEditId] = useState(null);
    const [notification, setNotification] = useState({
        show: false,
        message: '',
        type: 'success'
    });

    const [showDeleteConfirmModal, setShowDeleteConfirmModal] = useState(false);
    const [deleteIdToConfirm, setDeleteIdToConfirm] = useState(null);

    const { data: tableData = [], isLoading: isTableLoading, isError, refetch } = useGetSlotMastersQuery();
    const { data: maxSlotMasterId = 0, isLoading: isMaxIdLoading, refetch: refetchMaxId } = useGetMaxSlotMasterIdQuery();
    const [addSlot] = useAddSlotMasterMutation();
    const [updateSlot] = useUpdateSlotMasterMutation();
    const [deleteSlot] = useDeleteSlotMasterMutation();

    const showNotification = (message, type = 'success') => {
        setNotification({ show: true, message, type });
        setTimeout(() => {
            setNotification(prev => ({ ...prev, show: false }));
        }, 3000);
    };

    useEffect(() => {
        if (!editId && !isMaxIdLoading && isModalOpen) {
            const nextId = (typeof maxSlotMasterId === 'number' ? maxSlotMasterId : 0) + 1;
        }
    }, [maxSlotMasterId, isMaxIdLoading, editId, isModalOpen]);

    const handleAddNew = async () => {
        resetForm();
        setEditId(null);
        await refetchMaxId();
        setIsModalOpen(true);
    };

    const columns = [
        {
            header: 'Slot Master ID',
            accessor: 'SlotMasterId',
        },
        {
            header: 'Slot Name',
            accessor: 'SlotMaster_Name',
        },
        {
            header: 'Sponsor ID',
            accessor: 'SponsorMasterId',
        },
        {
            header: 'Sponsor Name',
            accessor: 'SponsorMaster_Name',
        },
        {
            header: 'Action',
            accessor: 'action',
            isAction: true,
            className: 'text-center',
            actionRenderer: (row) => (
                <div className="flex justify-center space-x-3">
                    <button
                        className="p-2 text-blue-600 bg-blue-50 rounded-md hover:bg-blue-100 transition-colors duration-200"
                        onClick={() => handleEdit(row)}
                        title="Edit"
                    >
                        <PencilSquareIcon className="h-5 w-5" />
                    </button>
                    <button
                        className="p-2 text-red-600 bg-red-50 rounded-md hover:bg-red-100 transition-colors duration-200"
                        onClick={() => handleDelete(row.SlotMasterId)}
                        title="Delete"
                    >
                        <Trash2 className="h-5 w-5" />
                    </button>
                </div>
            )
        }
    ];

    const handleInputChange = (e) => {
        const { name, value } = e.target;
        setFormData(prev => ({
            ...prev,
            [name]: value
        }));
    };

    const handleSubmit = async (e) => {
        e.preventDefault();
        try {
            if (editId) {
                // For update, we need to send the ID in the URL and the data in body
                await updateSlot({
                    id: editId,
                    SlotMaster_Name: formData.SlotMaster_Name,
                    SponsorMasterId: parseInt(formData.SponsorMasterId)
                }).unwrap();
                showNotification('Slot updated successfully!');
            } else {
                // For create, we don't send SlotMasterId (it's auto-generated by database)
                await addSlot({
                    SlotMaster_Name: formData.SlotMaster_Name,
                    SponsorMasterId: parseInt(formData.SponsorMasterId)
                }).unwrap();
                showNotification('Slot added successfully!');
            }
            resetForm();
            setIsModalOpen(false);
            refetch();
        } catch (error) {
            console.error('Failed to save slot:', error);
            showNotification('Failed to save slot!', 'error');
        }
    };

    const handleEdit = (row) => {
        setFormData({
            SlotMaster_Name: row.SlotMaster_Name,
            SponsorMasterId: row.SponsorMasterId?.toString() || '',
        });
        setEditId(row.SlotMasterId);
        setIsModalOpen(true);
    };

    const handleDelete = (SlotMasterId) => {
        setDeleteIdToConfirm(SlotMasterId);
        setShowDeleteConfirmModal(true);
    };

    const confirmDelete = async () => {
        try {
            const result = await deleteSlot(deleteIdToConfirm).unwrap();
            if (result && result.message) {
                showNotification('Slot deleted successfully!');
                refetch();
            } else {
                showNotification('Slot deleted successfully!');
                refetch();
            }
        } catch (error) {
            console.error('Failed to delete slot:', error);
            if (error.data) {
                if (error.data.detail) {
                    showNotification(error.data.detail, 'error');
                }
                else if (error.data.error) {
                    showNotification(error.data.error, 'error');
                }
                else {
                    showNotification('Failed to delete slot!', 'error');
                }
            } else {
                showNotification('Failed to delete slot!', 'error');
            }
        } finally {
            setShowDeleteConfirmModal(false);
            setDeleteIdToConfirm(null);
        }
    };

    const resetForm = () => {
        setFormData({
            SlotMaster_Name: '',
            SponsorMasterId: ''
        });
        setEditId(null);
    };

    if (isTableLoading) return <div className="min-h-screen bg-gray-50 flex items-center justify-center px-4">
        <div className="text-center space-y-4">
            <div className="w-12 h-12 border-4 border-blue-300 border-t-blue-600 rounded-full animate-spin mx-auto" />

            <p className="text-gray-700 text-lg font-medium">
                Loading
                <span className="inline-block animate-pulse ml-1 text-blue-600">...</span>
            </p>
        </div>
    </div>;
    if (isError) return <div className="text-center py-8 text-red-600">Error loading slots. Please try again.</div>;

    return (
        <div className="bg-gray-50 min-h-screen font-inter">
            {notification.show && (
                <div className={`fixed top-4 right-4 z-50 flex items-center p-4 rounded-md shadow-lg ${notification.type === 'success'
                    ? 'bg-green-50 text-green-800 border border-green-200'
                    : 'bg-red-50 text-red-800 border border-red-200'
                    }`}>
                    {notification.type === 'success' ? (
                        <CheckCircleIcon className="h-6 w-6 text-green-500 mr-2" />
                    ) : (
                        <XCircleIcon className="h-6 w-6 text-red-500 mr-2" />
                    )}
                    <span>{notification.message}</span>
                </div>
            )}

            <TableUtility
                headerContent={
                    <CreateNewButton onClick={handleAddNew} />
                }
                title="Slot Master"
                columns={columns}
                data={tableData}
                pageSize={10}
            />

            <Modal
                isOpen={isModalOpen}
                onClose={() => {
                    setIsModalOpen(false);
                    resetForm();
                }}
                title={editId ? 'Edit Slot' : 'Add New Slot'}
            >
                <form onSubmit={handleSubmit} className="space-y-4">
                    <div className="grid grid-cols-1 gap-4">
                        {editId && (
                            <div>
                                <label htmlFor="SlotMasterId" className="block text-sm font-medium text-gray-700 mb-1">
                                    Slot Master ID
                                </label>
                                <input
                                    id="SlotMasterId"
                                    type="number"
                                    value={editId}
                                    className="w-full px-3 py-2 bg-gray-100 border border-gray-300 rounded-md cursor-not-allowed"
                                    readOnly
                                    aria-label="Slot Master ID"
                                />
                                <p className="mt-1 text-xs text-gray-500">
                                    Slot ID (read-only for editing)
                                </p>
                            </div>
                        )}

                        {!editId && (
                            <div>
                                <label htmlFor="nextSlotId" className="block text-sm font-medium text-gray-700 mb-1">
                                    Next Available Slot ID
                                </label>
                                <input
                                    id="nextSlotId"
                                    type="number"
                                    value={isMaxIdLoading ? 'Loading...' : (maxSlotMasterId + 1)}
                                    className="w-full px-3 py-2 bg-gray-100 border border-gray-300 rounded-md cursor-not-allowed"
                                    readOnly
                                    aria-label="Next Available Slot ID"
                                />
                                <p className="mt-1 text-xs text-gray-500">
                                    Auto-generated by the system
                                </p>
                            </div>
                        )}

                        <div>
                            <label htmlFor="SlotMaster_Name" className="block text-sm font-medium text-gray-700 mb-1">
                                Slot Name *
                            </label>
                            <input
                                id="SlotMaster_Name"
                                type="text"
                                name="SlotMaster_Name"
                                value={formData.SlotMaster_Name}
                                onChange={handleInputChange}
                                autoComplete='off'
                                className="w-full px-3 py-2 text-gray-700 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-blue-500 transition duration-150"
                                required
                                placeholder="Enter slot name"
                            />
                        </div>

                        {/* <div>
                            <label htmlFor="SponsorMasterId" className="block text-sm font-medium text-gray-700 mb-1">
                                Sponsor ID *
                            </label>
                            <input
                                id="SponsorMasterId"
                                type="number"
                                name="SponsorMasterId"
                                value={formData.SponsorMasterId}
                                onChange={handleInputChange}
                                autoComplete='off'
                                className="w-full px-3 py-2 text-gray-700 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-blue-500 transition duration-150"
                                required
                                placeholder="Enter sponsor ID"
                                min="1"
                            />
                            <p className="mt-1 text-xs text-gray-500">
                                Enter the valid Sponsor Master ID
                            </p>
                        </div> */}
                    </div>

                    <div className="flex justify-end space-x-3 pt-4">
                        <button
                            type="button"
                            onClick={() => {
                                setIsModalOpen(false);
                                resetForm();
                            }}
                            className="px-4 py-2 border border-gray-300 rounded-md shadow-sm text-sm font-medium text-gray-700 bg-white hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500 transition-colors duration-200"
                        >
                            Cancel
                        </button>
                        <button
                            type="submit"
                            className="px-4 py-2 border border-transparent rounded-md shadow-sm text-sm font-medium text-white bg-blue-600 hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500 transition-colors duration-200"
                        >
                            {editId ? 'Update' : 'Save'}
                        </button>
                    </div>
                </form>
            </Modal>

            <Modal
                isOpen={showDeleteConfirmModal}
                onClose={() => setShowDeleteConfirmModal(false)}
                title="Confirm Deletion"
            >
                <div className="p-4 text-center">
                    <p className="text-lg text-gray-700 mb-6">Are you sure you want to delete this slot?</p>
                    <div className="flex justify-center space-x-4">
                        <button
                            type="button"
                            onClick={() => setShowDeleteConfirmModal(false)}
                            className="px-6 py-2 border border-gray-300 rounded-md shadow-sm text-sm font-medium text-gray-700 bg-white hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-gray-500 transition-colors duration-200"
                        >
                            Cancel
                        </button>
                        <button
                            type="button"
                            onClick={confirmDelete}
                            className="px-6 py-2 border border-transparent rounded-md shadow-sm text-sm font-medium text-white bg-red-600 hover:bg-red-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-red-500 transition-colors duration-200"
                        >
                            Delete
                        </button>
                    </div>
                </div>
            </Modal>
        </div>
    );
}

export default SlotMaster;